name: pooch
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - requests
    - packaging
    - appdirs
    - pysftp
    # Development requirements
    - pytest
    - pytest-cov
    - coverage
    - black
    - flake8
    - pylint
    - sphinx=2.2.1
    - sphinx_rtd_theme=0.4.3
