name: pooch
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - pip
    - requests
    - packaging
    - appdirs
    - tqdm
    # Development requirements
    - pytest
    - pytest-cov
    - coverage
    - black
    - flake8
    - pylint
    - sphinx=1.8.5
    - sphinx_rtd_theme
    - numpydoc
