# Linting and style checks with GitHub Actions
name: Style Checks

# Only build PRs and the master branch. Pushes to branches will only be built
# when a PR is opened.
on:
  pull_request:
  push:
    branches:
      - master

###############################################################################
jobs:

  black:
    name: black (format)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install flake8

      - name: List installed packages
        run: pip freeze

      - name: Formatting check (black and flake8)
        run: make black-check

  flake8:
    name: flake8 (style)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install flake8

      - name: List installed packages
        run: pip freeze

      - name: Formatting check (black and flake8)
        run: make flake8

  pylint:
    name: pylint (style)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install pylint==2.4.*

      - name: List installed packages
        run: pip freeze

      - name: Linting (pylint)
        run: make lint
